version: '3'
services:
  # ############## nginx ##############
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/Dockerfile
  #   depends_on:
  #     - web
  #   volumes:
  #     - .:/app:cached
  #   ports:
  #     - 80:80

  ############## web ##############
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - bundle:/user/local/bin
    links:
      - db
      # - redis
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: sample
      DATABASE_PASSWORD: password
      DATABASE_NAME: rails_app_develop
      TEST_DATABASE_HOST: db
      TEST_DATABASE_PORT: 3306
      TEST_DATABASE_USERNAME: root
      TEST_DATABASE_PASSWORD: password
      TEST_DATABASE_NAME: rails_app_test
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    networks:
      - default
  ############## mysql ##############
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sample
      MYSQL_PASSWORD: password
    volumes:
      - ./tmp/docker/mysql:/var/lib/mysql:delegated
    networks:
      - default

  # ############## redis ##############
  # redis:
  #   image: redis:latest

volumes:
  bundle:
